### ISSUE TITLE
Update the Docker file

### ISSUE THREAD

**Issue by BananaDev50** [MovieCast/api#3]
I am not really familiar with Docker yet, so could you update the Docker file for me @SebastianMalek
It should install gulp by the command `npm install -g gulp`, and run the command `gulp build`, to compile the es6 code.

**Comment by SebastianMalek** [comment]
do we need mongodb?

**Comment by BananaDev50** [comment]
Yea

**Comment by SebastianMalek** [comment]
In that case, I'd rather set the trakt.tv key as an environment variable... That's the only way to pass it through Docker. Otherwise you need to compile the Docker image yourself.

**Comment by BananaDev50** [comment]
Okay go for the environment variable then, just tell me how u're going to call it.
Maybe something like CFG_APIS_TRAKT_KEY, which directs in the code to config.apis.trakt.key

**Comment by SebastianMalek** [comment]
got everything to work except mongodb doesn't start for some reason...

**Comment by ItsDizzy** [comment]
Seems like this is done.
